apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: talkingdb-release
  title: TalkingDB Release Pipeline
  description: Trigger release + optional docker build for TalkingDB repos
spec:
  type: service
  owner: user:default/mayank.g

  parameters:
    - title: Release Configuration
      required:
        - hostSubdomain
      properties:
        hostSubdomain:
          type: string
          title: Host Subdomain
          description: Will be used as <subdomain>.talkingdb.io

        base-tdb-models-branch:
          type: string
          title: base-tdb-models branch
          default: main

        base-tdb-clients-branch:
          type: string
          title: base-tdb-clients branch
          default: main

        base-tdb-helpers-branch:
          type: string
          title: base-tdb-helpers branch
          default: main

        package-content-elementizer-branch:
          type: string
          title: package-content-elementizer branch
          default: main

        module-ttt-branch:
          type: string
          title: module-ttt branch
          default: main

    - title: Docker Configuration
      properties:
        docker_elementizer:
          type: boolean
          title: Build Docker for package-content-elementizer
          default: false

        docker_module_ttt:
          type: boolean
          title: Build Docker for module-ttt
          default: true

        elementizer_tag:
          type: string
          title: package-content-elementizer Docker Tag
          description: Required only if Docker build is enabled

        module_ttt_tag:
          type: string
          title: module-ttt Docker Tag
          description: Required only if Docker build is enabled

  steps:
    - id: trigger
      name: Trigger GitHub Workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=infra-tdb-platform&owner=TalkingDB
        workflowId: sync.yml
        branchOrTagName: main
        workflowInputs:
          host: "${{ parameters.hostSubdomain }}.talkingdb.io"

          repos_json: >
            [
              { "url": "https://github.com/TalkingDB/base-tdb-models.git", "branch": "${{ parameters.base-tdb-models-branch }}" },
              { "url": "https://github.com/TalkingDB/base-tdb-clients.git", "branch": "${{ parameters.base-tdb-clients-branch }}" },
              { "url": "https://github.com/TalkingDB/base-tdb-helpers.git", "branch": "${{ parameters.base-tdb-helpers-branch }}" },
              { "url": "https://github.com/TalkingDB/package-content-elementizer.git", "branch": "${{ parameters.package-content-elementizer-branch }}" },
              { "url": "https://github.com/TalkingDB/module-ttt.git", "branch": "${{ parameters.module-ttt-branch }}" },
            ]

          docker_module_ttt: "${{ parameters.docker_module_ttt }}"
          docker_elementizer: "${{ parameters.docker_elementizer }}"

          module_ttt_tag: "${{ parameters.module_ttt_tag || '' }}"
          elementizer_tag: "${{ parameters.elementizer_tag || '' }}"
  output:
    text:
      - title: Triggered
        content: Release pipeline triggered for ${{ parameters.hostSubdomain }}.talkingdb.io
